#!/usr/bin/env node
import * as fs from "node:fs/promises";

const VERSION_TS = "src/version.ts";

const packageJsonString = await fs.readFile("package.json", "utf8");
const packageJson = JSON.parse(packageJsonString);

await fs.writeFile(
  VERSION_TS,
  `\
// This file is autogenerated by /scripts/postversion.mjs
export const version = ${JSON.stringify(packageJson.version)};
`,
);